# Site Info
title:              "ZehraH"
description:        "Zehrah's Blog"
author_name:        "Zehra Hayirci" # change this to your name
logo_url:           https://avatars0.githubusercontent.com/u/13794983?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                http://ozansener.net/ # main url
baseurl:            /jekyll-now
permalink:          /:title # Post permalink
timezone:           Asia/Tokyo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap

# Includes an icon in the footer for each username you enter
footer-links:
  instagram: https://www.instagram.com/tokyoda100gun/
  twitter: zezesbookmarks



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
